language: python  
python:  
  - "3.8"  
dist: bionic  # Ubuntu 18.04 (поддерживает Java 8, необходимую для Android SDK)  

before_install:  
  - sudo apt-get update  
  - sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev  

install:  
  - pip install --upgrade pip virtualenv  
  - pip install buildozer cython==0.29.19 kivy  

script:  
  - buildozer init  
  - echo "requirements = python3,kivy,pyftpdlib,android" > buildozer.spec  
  - buildozer android debug  

deploy:  
  provider: releases  
  api_key: $GITHUB_TOKEN  
  file: bin/*.apk  
  skip_cleanup: true  
  on:  
    tags: true  
